# Changes here will be overwritten by Copier
_commit: v0.3.4
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage git loader
distribution_name: swh-loader-git
have_cli: false
have_workers: true
package_root: swh/loader/git
project_name: swh.loader.git
python_minimal_version: '3.10'
readme_format: rst
