# -*- makefile -*-
NOSEFLAGS=--nologcapture -v
DB_TEST=$(DB)-test
TESTDIR = ./swh/tests

test-connect-db:
	psql $(DB_TEST)

test-create-db:
	cd $(SQL_FOLDER) && make clean initdb DBNAME=$(DB_TEST)

test-drop-db:
	cd $(SQL_FOLDER) && make clean dropdb DBNAME=$(DB_TEST)

test-cleandb:
	PYTHONPATH=$(_PYPATH) $(SWH_DB_MANAGER) $(FLAG) --config ./resources/test/db-manager.ini cleandb

test-check-meta:
	@echo "DB $(DB_TEST) metadata:"
	@$(BINDIR)/db-git-repo-meta.sh $(DB_TEST)
	@echo

tests:
	PYTHONPATH=$(_PYPATH) make test

test-run-back:
	PYTHONPATH=$(_PYPATH) $(SWH_BACK) $(FLAG) --config ./resources/test/back.ini

test-http:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_http.py

test-swhrepo:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_swhrepo.py

test-api:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api*.py

test-api-post-per-type:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_post_*.py

test-api-content:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_content.py

test-api-directory:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_directory.py

test-api-revision:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_revision.py

test-api-release:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_release.py

test-api-occurrence:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_occurrence.py

test-api-home:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_home.py

test-api-origin:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_origin.py

test-api-person:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_person.py

test-file:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_file.py

test-remote-loader:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_remote_loader.py

test-local-loader:
	PYTHONPATH=$(_PYPATH) $(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_local_loader.py

test-loaders: test-local-loader test-remote-loader
