# -*- makefile -*-
NOSEFLAGS=--nologcapture -v
DB_TEST=$(DB)-test
TESTDIR = ./swh/loader/git/tests

test-connect-db:
	psql $(DB_TEST)

test-create-db:
	make -C $(SQL_FOLDER) clean initdb DBNAME=$(DB_TEST)

test-drop-db:
	make -C $(SQL_FOLDER) clean dropdb DBNAME=$(DB_TEST)

test-cleandb:
	$(SWH_DB_MANAGER) $(FLAG) --config ./resources/test/db-manager.ini cleandb

test-clean:
	rm -rf /tmp/swh-loader-git/test/

test-prepare:
	mkdir -p /tmp/swh-loader-git/test/

test-log-back:
	tail $(FOLLOW_LOG) /tmp/swh-loader-git/test/log/back.log

test-check-meta:
	@echo "DB $(DB_TEST) metadata:"
	@$(BINDIR)/db-git-repo-meta.sh $(DB_TEST)
	@echo

test-run-back:
	$(SWH_BACK) $(FLAG) --config ./resources/test/back.ini

test-http:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_http.py

test-swhrepo:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_swhrepo.py

test-api:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api*.py

test-api-post-per-type:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_post_*.py

test-api-content:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_content.py

test-api-directory:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_directory.py

test-api-revision:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_revision.py

test-api-release:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_release.py

test-api-occurrence:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_occurrence.py

test-api-home:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_home.py

test-api-origin:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_origin.py

test-api-person:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_api_person.py

test-file:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_file.py

test-remote-loader:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_remote_loader.py

test-local-loader:
	$(NOSE) $(NOSEFLAGS) $(TESTDIR)/test_local_loader.py

test-loaders: test-local-loader test-remote-loader
